### ISSUE TITLE
Getting Internal Server Error

### ISSUE THREAD

**Issue by marijana** [carlcs/craft-dateperiod#1]
Tried using the plugin exactly like its written in this post:
http://craftcms.stackexchange.com/questions/9611/list-months-between-a-given-date-range

but getting the following:

Internal Server Error

DatePeriod::__construct(): This constructor accepts either (DateTime, DateInterval, int) OR (DateTime, DateInterval, DateTime) OR (string) as arguments.

Tried several different aproaches and different date formats but always the same error.
I am on PHP 5.4

Do you know how to fix this?

Thanks a lot in advance for any info!

**Comment by carlcs** [comment]
Hello. You currently need to pass in DateTime objects. If you have a string representing a date, use the Twig `date()` function to convert it.

e.g.: `{% set startDate = date('2015-12-01') %}`

**Comment by marijana** [comment]
Hi,
Works like a charm! Thanks!

One additional question:

I have dates like this: 
Tue Dec 01 2015 00:00:00 - Thu Dec 10 2015 00:00:00

Plugin returns all days except last one, like this:
01.12.2015
02.12.2015
03.12.2015
04.12.2015
05.12.2015
06.12.2015
07.12.2015
08.12.2015
09.12.2015

and I need the last day aswell.

I have solved this with modifying the endDate like this:
{% set endDate = date.end|date_modify("+1 day") %}
and then passing it to date() function and plugin

I have a lot of dates and it seems to run a bit slow.

Is there a better solution?

Thanks again!

**Comment by carlcs** [comment]
I don't think you need to use both `date()` and `date_modify()`, one function should be enough.

Regarding the last day problem, that's how DatePeriods are meant to work, they return every second / moment in-between the dates, but not the end-moment itself. Your fix is a good idea depending on the use-case; it's even a recommended solution on php.net (→ http://php.net/manual/de/class.dateperiod.php).

Your speed problems are most likely caused by something else. I'm pretty sure `date_modify` and `datePeriod` don't have a noticeable impact on performance and it's probably the database queries, which are responsible for that (Matrix field or a relations field involved?). To improve performance you could cache the whole page or each period individually, e.g., `{% cache using key 'date-' ~ someUniqueId %}`.

**Comment by marijana** [comment]
Thanks a lot for everything!
Happy crafting!
